micronaut:
  application:
    name: melikotlin
cassandra:
  default:
    basic:
      contact-points:
        - localhost:9042
      session-keyspace: ecommerce
      load-balancing-policy:
        local-datacenter: datacenter1